rules:
  comma-dangle:
    - 0
  no-empty:
    - 0
  no-console:
    - 2
    - allow:
      - warn
      - error
  no-unused-vars:
    - 2
    - args: all
      argsIgnorePattern: ^_

env:
  browser: true
  es6: true
  amd: true

globals:
  _: true
  $: true
  JSZip: true
  Backbone: true
  CodeMirror: true
  widget: true

extends: 'eslint:recommended'
